//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3.User.Utilities {
    
    
    public partial class ChuongControl {
        
        /// <summary>
        /// ThongTinTruyenControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Project3.User.Chuong.ThongTinTruyenControl ThongTinTruyenControl;
        
        /// <summary>
        /// DSChuongControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Project3.User.Chuong.DSChuongControl DSChuongControl;
    }
}
